name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
                include: 
                    - node-version: 18
                      operating-system: ubuntu-latest
                exclude:
                    - node-version: 12
                      operating-system: windows-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: install depend
              run: npm ci
            - name: buiild project
              run: npm run build